name: Deploy to Ubuntu Server

env:
  ACTIONS_STEP_DEBUG: false

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Actions
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: oakis/rust-map-api:latest

      - name: Create SSH Key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: /home/runner/.ssh/id_rsa
          script: |
            # Clean up unused Docker images
            docker image prune -a --force
            # Pull and run the latest Docker image
            docker pull oakis/rust-map-api:latest
            docker stop rust-map-api || true
            docker rm rust-map-api || true
            docker run -d -p 3001:3001 --name rust-map-api oakis/rust-map-api:latest
